version: "3"

services:
  #PHP Service
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: priceplan
    container_name: priceplan-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/priceplan/
    volumes:
      - ./:/var/www/priceplan/
      - ./docker-compose/php:/usr/local/etc/php/conf.d/
    networks:
      - priceplan-network
    
  #nginx service
  webserver:
    image: nginx:alpine
    container_name: priceplan-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/priceplan/
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - priceplan-network
    
  #database service
  db:
    image: mysql:8.0
    container_name: priceplan-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    networks:
      - priceplan-network

networks:
  priceplan-network:
    driver: bridge